engines:
  checkstyle:
    enabled: true
    channel: "beta" 
    config: 'checkstyle.xml'
    checks:
      com.puppycrawl.tools.checkstyle.checks.blocks.NeedBracesCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.naming.PackageNameCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocMethodCheck:
        enabled: false
      com.puppycrawl.tools.checkstyle.checks.blocks.RightCurlyCheck:
        enabled: false
ratings:
  paths:
- "**.java"